-- begin PETS_USERS
create unique index IDX_PETS_USERS_UNIQ_LOGIN on PETS_USERS (login)^
-- end PETS_USERS
-- begin PETS_TABLE_LIST_PETS2
alter table PETS_TABLE_LIST_PETS2 add constraint FK_PETS_TABLE_LIST_PETS2_ON_PETS_ID_SHELTER foreign key (PETS_ID_SHELTER) references PETS_TABLE_SHELTER(ID)^
create index IDX_PETS_TABLE_LIST_PETS2_ON_PETS_ID_SHELTER on PETS_TABLE_LIST_PETS2 (PETS_ID_SHELTER)^
-- end PETS_TABLE_LIST_PETS2
